######################################################################
### ANALYSIS OF NEURONAL RESPONSES TO EVENTS IN CUED APPROACH TASK ###
######################################################################

# Have a folder with the following functions: nexreaderwaves.rFunc, neuraldataextract.rFunc, eventfinder.rFunc and this one (MV neural histograms)

### I have to run a bunch of functions before running this:
# - neuraldataxtract.R (this will give me the names of all my variables, etc.). For this function to work properly, I need to name my NEX files following this template: "120616_MV150_Session 1" (MMDDYY_MVrat#_Session #of session"). The MV part of the code needs to be changed if your rats have a different "first name". 
# - eventfinder.R (this will give me an index of values that I can input into my neuralhist.rFunc to indicate the program the task events that I want to look into)


## This function is going to give me the average firing per bin throughout the session (same thing I get by exporting the data to excel from NEX). If I want a complete list of the timestamps and all that, I can just run the lines of code defining "nexdata", "neurons" (for just neuronal timestamps) or "events" (just beh timestamps)

################ BEFORE YOU RUN THE FUNCTION, SELECT THE PARAMETERS:

## Code for events (the number has to be entered in the neuralhist function):
#1 = DS_onset 
#2 = NS_onset 
#3 = Entry 
#4 = Exit
#5 = DSonset_Entered
#6 = DSonset_Missed
#7 = NSonset_Entered
#8 = NSonset_Missed
#9 = Entry_DS
#10 = Entry_ITI
#11 = Exit_PostRew
#12 = Cue
#13 = Baseline_trials
#14 = Entry_NS
#15 = Entry_DS_Long #DS entries (rewarded) that were longer than a set threshold (default = 2s, for changing it go to neuraldataextract script)



### Set wd
setwd("C:/Users/mvega/Dropbox/DISSERTATION/")
setwd("C:/Users/Mercedes/Dropbox/DISSERTATION/")
setwd("E:/Dropbox/DISSERTATION/")

### Before running the function, define where the NEX files are
NEXfilesSource <- paste(getwd(), "/Experiment 4/Neuronal data/NEX files/", sep="")

### Load necessary functions
functionFolder <- paste(getwd(), "/ALL HYBRID/Functions/", sep="")
load(file = paste(functionFolder, "neuralhist.r", sep=""))
# 
# ### More parameters
# 
# path <- NEXfilesSource
# startt <- 0
# endt <- 10000 #just in case
# binw <- 50 #in ms
# psthmin <- 2 #in s
# psthmax <- 2 #in s
# cueexonly <- F #do you want data from cue-excited neurons only?
# allResults <- T #do you want all the objects generated by this function?
# 
# 
# 
# ###################### DS onset################################
# #Choose event code:
# event <- 1 # See codes above

#### Function itself
# allNeurons = neuralhist (path=NEXfilesSource, sessionInterval="all", event=8, startt=0,endt=10000, binw=50, psthmin=2, psthmax=2,cueexonly=F, allResults=T)
####

allNeuronsDS = neuralhist (path=NEXfilesSource, event=1, startt=0,endt=10000, binw=50, psthmin=10, psthmax=10,cueexonly=F, allResults=T)
allNeuronsNS = neuralhist (path=NEXfilesSource, event=2, startt=0,endt=10000, binw=50, psthmin=10, psthmax=10,cueexonly=F, allResults=T)

allNeuronsDSresponded = neuralhist (path=NEXfilesSource, event=5, startt=0,endt=10000, binw=50, psthmin=10, psthmax=10,cueexonly=F, allResults=T)
allNeuronsNSresponded = neuralhist (path=NEXfilesSource, event=7, startt=0,endt=10000, binw=50, psthmin=10, psthmax=10,cueexonly=F, allResults=T)

allNeuronsDSmissed = neuralhist (path=NEXfilesSource, event=6, startt=0,endt=10000, binw=50, psthmin=10, psthmax=10,cueexonly=F, allResults=T)
allNeuronsNSmissed = neuralhist (path=NEXfilesSource, event=8, startt=0,endt=10000, binw=50, psthmin=10, psthmax=10,cueexonly=F, allResults=T)

### BEHAVIOR
dataforRdir <- 'E:/Dropbox/DISSERTATION/Experiment 4/Data for R/'
load(paste(dataforRdir, "csacqidx.ridx", sep=""))
load(paste(dataforRdir, "alldata.rdat", sep=""))
load(paste(dataforRdir, "rats.rdat", sep=""))
load(paste(dataforRdir, "idx.rdat", sep=""))


summRR <-select(csacqidx, subject, session, group, DSperc, NSperc, LatencyCSplus, LatencyCSminus, CSplusTaskAcc, CSminusTaskAcc)


### ENTRIES
allNeuronsEntryDS = neuralhist (path=NEXfilesSource, event=9, startt=0,endt=10000, binw=50, psthmin=2, psthmax=10,cueexonly=F, allResults=T)
allNeuronsEntryNS = neuralhist (path=NEXfilesSource, event=14, startt=0,endt=10000, binw=50, psthmin=2, psthmax=10,cueexonly=F, allResults=T)
allNeuronsEntryITI = neuralhist (path=NEXfilesSource, event=10, startt=0,endt=10000, binw=50, psthmin=2, psthmax=10,cueexonly=F, allResults=T)
allNeuronsEntryDSLong = neuralhist (path=NEXfilesSource, event=15, startt=0,endt=10000, binw=50, psthmin=2, psthmax=10,cueexonly=F, allResults=T)


## PLOT SCATTERPLOTS WITH PERFORMANCE ON THE X AXIS AND FR IN THE Y AXIS
# Figure out the parameters that were used on the function to generate the data in "allNeurons"
binw <- allNeuronsDS$parameters$binw
psthmin <- allNeuronsDS$parameters$psthmin
psthmax <- allNeuronsDS$parameters$psthmax

#### ESTABLISHING BL AND TARGET PERIODS WHEN THE EVENT IS THE CUE
# In firingmat, the rows are the bins. Define the "POST CUE" bins (those AFTER the cue)
firstBin <-(psthmin*1000/binw)+1 #Second bin after the cue (50ms)
lastBin <- (psthmin*1000/binw)+11 #10 bins of 50ms (500ms) after the cue
CUEperiod <- (length(firstBin:lastBin)*binw)

# Bins to be used as baseline
BLfirstBin <-(psthmin*1000/binw)-(psthmin*1000/binw)+1
BLlastBin <- (psthmin*1000/binw)
BLperiod <- (length(BLfirstBin:BLlastBin)*binw)/1000


#### ESTABLISHING BL AND TARGET PERIODS WHEN THE EVENT IS ENTRY DURING DS OR ITI ENTRIES
# Figure out the parameters that were used on the function to generate the data in "allNeurons"
binw <- allNeuronsEntryDS$parameters$binw
psthmin <- allNeuronsEntryDS$parameters$psthmin
psthmax <- allNeuronsEntryDS$parameters$psthmax


# In firingmat, the rows are the bins. Define the "POST ENTRY" bins (those AFTER the entry)
firstBin <-(psthmin*1000/binw)+1 #Second bin after the entry (50ms)
lastBin <- (psthmin*1000/binw)+40 #40 bins of 50ms (2000ms or 2s) after entry (based on PETH, there might be signals until 2s after entry)
ENTRYperiod <- (length(firstBin:lastBin)*binw) #I'm calling it CUEperiod but it's the target period after entry (2s)

# # Bins to be used as baseline
# SecPostEntryMin <- 8 #in sec
# SecPostEntryMax <- 10 #in sec
# BLfirstBin <-((psthmin+SecPostEntryMin)*1000/binw)
# BLlastBin <- ((psthmin+SecPostEntryMax)*1000/binw)
# BLperiod <- (((length(BLfirstBin:BLlastBin)-1)*binw)/1000) #in sec
# 



# Turn firingmat into Z scores
zscore <- function (x, avg, sd){(x-avg)/sd}

#ALL trials
ZDS <- c()
for(i in 1:ncol(allNeuronsDS$firingmat)){
        ZDS<- cbind(ZDS, zscore(allNeuronsDS$firingmat[,i], 
                                                  avg=mean(allNeuronsDS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                                  sd=sd(allNeuronsDS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}
ZNS <- c()
for(i in 1:ncol(allNeuronsNS$firingmat)){
        ZNS<- cbind(ZNS, zscore(allNeuronsNS$firingmat[,i], 
                                                  avg=mean(allNeuronsNS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                                  sd=sd(allNeuronsNS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}


# Responded trials
ZDSresponded <- c()
for(i in 1:ncol(allNeuronsDSresponded$firingmat)){
        ZDSresponded<- cbind(ZDSresponded, zscore(allNeuronsDSresponded$firingmat[,i], 
                                            avg=mean(allNeuronsDSresponded$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                            sd=sd(allNeuronsDSresponded$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}

ZNSresponded <- c()
for(i in 1:ncol(allNeuronsNSresponded$firingmat)){
        ZNSresponded<- cbind(ZNSresponded, zscore(allNeuronsNSresponded$firingmat[,i], 
                                            avg=mean(allNeuronsNSresponded$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                            sd=sd(allNeuronsNSresponded$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}

#Missed trials
ZDSmissed <- c()
for(i in 1:ncol(allNeuronsDSmissed$firingmat)){
        ZDSmissed<- cbind(ZDSmissed, zscore(allNeuronsDSmissed$firingmat[,i], 
                                          avg=mean(allNeuronsDSmissed$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                          sd=sd(allNeuronsDSmissed$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
  ))}

ZNSmissed <- c()
for(i in 1:ncol(allNeuronsNSmissed$firingmat)){
        ZNSmissed<- cbind(ZNSmissed, zscore(allNeuronsNSmissed$firingmat[,i], 
                          avg=mean(allNeuronsNSmissed$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                          sd=sd(allNeuronsNSmissed$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}



# FIRING AROUND TIME OF DIFFERENT KINDS OF ENTRY
ZEntryDS <- c()
for(i in 1:ncol(allNeuronsEntryDS$firingmat)){
        ZEntryDS<- cbind(ZEntryDS, zscore(allNeuronsEntryDS$firingmat[,i], 
                                avg=mean(allNeuronsEntryDS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                sd=sd(allNeuronsEntryDS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}


ZEntryDSLong <- c()
for(i in 1:ncol(allNeuronsEntryDSLong$firingmat)){
        ZEntryDSLong<- cbind(ZEntryDSLong, zscore(allNeuronsEntryDSLong$firingmat[,i], 
                                avg=mean(allNeuronsEntryDSLong$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                sd=sd(allNeuronsEntryDSLong$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}


ZEntryNS <- c()
for(i in 1:ncol(allNeuronsEntryNS$firingmat)){
        ZEntryNS<- cbind(ZEntryNS, zscore(allNeuronsEntryNS$firingmat[,i], 
                                          avg=mean(allNeuronsEntryNS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                          sd=sd(allNeuronsEntryNS$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}

ZEntryITI <- c()
for(i in 1:ncol(allNeuronsEntryITI$firingmat)){
        ZEntryITI<- cbind(ZEntryITI, zscore(allNeuronsEntryITI$firingmat[,i], 
                                          avg=mean(allNeuronsEntryITI$firingmat[BLfirstBin:BLlastBin, i], na.rm=T), 
                                          sd=sd(allNeuronsEntryITI$firingmat[BLfirstBin:BLlastBin, i], na.rm=T) 
        ))}



### Create data frame with data around time of CUE

toplot0 <- data.frame(ZDS = round(colMeans(ZDS[firstBin:lastBin,]),2), 
                      ZNS = round(colMeans(ZNS[firstBin:lastBin,]),2)
)

toplot1 <- data.frame(ZDSresponded = round(colMeans(ZDSresponded[firstBin:lastBin,]),2), 
                      ZNSresponded = round(colMeans(ZNSresponded[firstBin:lastBin,]),2)
)

toplot2 <- data.frame(ZDSmissed = round(colMeans(ZDSmissed[firstBin:lastBin,]),2), 
                     ZNSmissed = round(colMeans(ZNSmissed[firstBin:lastBin,]),2)
                    )

neuronIdx <- c()
for(i in 1:length(allNeuronsDS$neurons)){
        a <- rep(i, length(allNeuronsDS$neurons[[i]]))
        neuronIdx <- c(neuronIdx, a)
}

expandDF <- function(x, idx){
        newDF <- c()
        for(i in 1:ncol(x)){
                newCol <- c()
                for(j in 1:length(idx)){
                        a<- x[,i][idx[j]]
                        newCol <- c(newCol, a)
                }
                newDF <- cbind(newDF, newCol)
        }
        colnames(newDF) <- colnames(x)
        print(newDF)
}

toplot <- cbind(expandDF(summRR, neuronIdx), toplot1, toplot2)

save(file=paste(getwd(), "/Experiment 4/Data for R/allFRandBEHinZsc.rdat", sep=""), toplot)



### Create data frame with data around time of ENTRY
toplot0 <- data.frame(ZEntryDS = round(colMeans(ZEntryDS[firstBin:lastBin,]),2), 
                      ZEntryDSLong = round(colMeans(ZEntryDSLong[firstBin:lastBin,]),2),
                      ZEntryNS = round(colMeans(ZEntryNS[firstBin:lastBin,]),2), 
                      ZEntryITI = round(colMeans(ZEntryDS[firstBin:lastBin,]),2)
)

neuronIdx <- c()
for(i in 1:length(allNeuronsEntryDS$neurons)){
        a <- rep(i, length(allNeuronsEntryDS$neurons[[i]]))
        neuronIdx <- c(neuronIdx, a)
}

expandDF <- function(x, idx){
        newDF <- c()
        for(i in 1:ncol(x)){
                newCol <- c()
                for(j in 1:length(idx)){
                        a<- x[,i][idx[j]]
                        newCol <- c(newCol, a)
                }
                newDF <- cbind(newDF, newCol)
        }
        colnames(newDF) <- colnames(x)
        print(newDF)
}

toplot <- cbind(expandDF(summRR, neuronIdx), toplot0)
save(file=paste(getwd(), "/Experiment 4/Data for R/allFRandBEHinZscENTRYDATA.rdat", sep=""), toplot)


## SAVE ENTRY DATA FOR HEATMAPS
save(file=paste(getwd(), "/Experiment 4/Data for R/DSentryALL.rdat", sep=""), allNeuronsEntryDS)
save(file=paste(getwd(), "/Experiment 4/Data for R/DSentryALLlong.rdat", sep=""), allNeuronsEntryDSLong)
save(file=paste(getwd(), "/Experiment 4/Data for R/ITIentryALL.rdat", sep=""), allNeuronsEntryITI)
save(file=paste(getwd(), "/Experiment 4/Data for R/NSentryALL.rdat", sep=""), allNeuronsEntryNS)
firingmatDSentry <- allNeuronsEntryDS$firingmat
firingmatDSentryLong <- allNeuronsEntryDSLong$firingmat
firingmatNSentry <- allNeuronsEntryNS$firingmat
firingmatITIentry <- allNeuronsEntryITI$firingmat
save(file=paste(getwd(), "/Experiment 4/Data for R/DSentry.rdat", sep=""), firingmatDSentry)
save(file=paste(getwd(), "/Experiment 4/Data for R/DSentryLong.rdat", sep=""), firingmatDSentryLong)
save(file=paste(getwd(), "/Experiment 4/Data for R/NSentry.rdat", sep=""), firingmatNSentry)
save(file=paste(getwd(), "/Experiment 4/Data for R/ITIentry.rdat", sep=""), firingmatITIentry)

save(file=paste(getwd(), "/Experiment 4/Data for R/ZscDSentry.rdat", sep=""), ZEntryDS) #DS fIRINGMAT IN ZSC
save(file=paste(getwd(), "/Experiment 4/Data for R/ZscDSentryLong.rdat", sep=""), ZEntryDSLong) #DS long (exclude short entries) fIRINGMAT IN ZSC
save(file=paste(getwd(), "/Experiment 4/Data for R/ZscNSentry.rdat", sep=""), ZEntryNS) #NS fIRINGMAT IN ZSC
save(file=paste(getwd(), "/Experiment 4/Data for R/ZscITIentry.rdat", sep=""), ZEntryITI) #ITI entry firingmat in Zsc




#######################
# BASELINE
# Bins to be used as baseline
BLfirstBin <-(psthmin*1000/binw)-(psthmin*1000/binw)+1
BLlastBin <- (psthmin*1000/binw)
BLperiod <- (length(BLfirstBin:BLlastBin)*binw)/1000

#Responded trials
BLDSresponded <- c()
for(i in 1:ncol(allNeuronsDSresponded$firingmat)){
  BLDSresponded<- cbind(BLDSresponded, allNeuronsDSresponded$firingmat[BLfirstBin:BLlastBin, i])}

BLNSresponded <- c()
for(i in 1:ncol(allNeuronsNSresponded$firingmat)){
  BLNSresponded<- cbind(BLNSresponded,allNeuronsNSresponded$firingmat[BLfirstBin:BLlastBin, i])}

#Missed trials
BLDSmissed <- c()
for(i in 1:ncol(allNeuronsDSmissed$firingmat)){
  BLDSmissed<- cbind(BLDSmissed, allNeuronsDSmissed$firingmat[BLfirstBin:BLlastBin, i])}

BLNSmissed <- c()
for(i in 1:ncol(allNeuronsNSmissed$firingmat)){
  BLNSmissed<- cbind(BLNSmissed, allNeuronsNSmissed$firingmat[BLfirstBin:BLlastBin, i])}


toplot1 <- data.frame(BLDSresponded = round(colMeans(BLDSresponded),2), 
                      BLNSresponded = round(colMeans(BLNSmissed),2)
)


toplot2 <- data.frame(BLDSmissed = round(colMeans(BLDSmissed),2), 
                      BLNSmissed = round(colMeans(BLNSmissed),2)
)

neuronIdx <- c()
for(i in 1:length(allNeuronsDS$neurons)){
  a <- rep(i, length(allNeuronsDS$neurons[[i]]))
  neuronIdx <- c(neuronIdx, a)
}

expandDF <- function(x, idx){
  newDF <- c()
  for(i in 1:ncol(x)){
    newCol <- c()
    for(j in 1:length(idx)){
      a<- x[,i][idx[j]]
      newCol <- c(newCol, a)
    }
    newDF <- cbind(newDF, newCol)
  }
  colnames(newDF) <- colnames(x)
  print(newDF)
}

behANDneu <- cbind(expandDF(summRR, neuronIdx), toplot1, toplot2)

save(behANDneu, file = paste(getwd(), "/ALL HYBRID/Data for R/behANDneuBLNoInf.rdat", sep=""))










#### ACCURACY AND FIRING
#Neurons #57 and 80 are outliers, they make it difficult to see the relationship
plot.new()
plot(x=toplot$DSRR, y=toplot$ZDSresponded, col="darkblue", bg="darkblue", pch=16, cex=2,
     xlab="DS response ratio", ylab="Post cue (400ms) firing (Z-sc.)", cex.lab=1.5, font.lab=2, ylim=c(-2, 20))
plot(x=toplot$DSRR, y=toplot$ZDSmissed, col="steelblue", bg="steelblue", pch=16, cex=2,
     xlab="DS response ratio", ylab="Post cue (400ms) firing (Z-sc.)", cex.lab=1.5, font.lab=2, ylim=c(-2, 20))
plot(x=toplot$DSRR[-c(57, 80)], y=toplot$ZDSmissed[-c(57, 80)], col="steelblue", bg="steelblue", pch=16, cex=2,
     xlab="DS response ratio", ylab="Post cue (400ms) firing (Z-sc.)", cex.lab=1.5, font.lab=2, ylim=c(-2, 20))





install.packages("scatterplot3d")
library("scatterplot3d")
#FIRING VS. DSRR
scatterplot3d(x=toplot$TOTALresp, z=toplot$ZDS, y=toplot$Accuracy[-c(57, 80)], pch=19, color="steelblue", type="h")

install.packages("rgl")
library(rgl)
plot3d(x=toplot$DSRR, z=toplot$ZDS, y=toplot$NSRR, xlab="DS response ratio", zlab="Post-cue (400ms) firing rate (Z-sc)", ylab="NS response ratio", type="p", size=6, col="steelblue", zlim=c(min(toplot), 12), box=T)
axes3d(edges="bbox", labels=T)

plot3d(x=toplot$DSRR, z=toplot$ZNS, y=toplot$NSRR, xlab="DS response ratio", zlab="Post-cue (400ms) firing rate (Z-sc)", ylab="NS response ratio", type="p", size=6, col="indianred", zlim=c(min(toplot), 12), box=T, add=T)

#FIRING VS. DSRR
plot.new()
plot.window(xlim=c(0, 1), ylim=c(min(toplot), 12))
colors <- c("steelblue", "indianred")
points(x=toplot$DSRR, y=toplot$ZDS, pch=19, col=colors[1])
points(x=toplot$DSRR, y=toplot$ZNS, pch=19, col=colors[2])
axis(1, at=seq(0, 1, by=0.1), lab=seq(0, 1, by=0.1))
axis(2, at=seq(round(min(toplot), 0), 12, 1))

#FIRING VS. ACCURACY
plot.new()
plot.window(xlim=c(0, 1), ylim=c(min(toplot), 12))
colors <- c("steelblue", "indianred")
points(x=toplot$Accuracy, y=toplot$ZDS, pch=19, col=colors[1])
points(x=toplot$Accuracy, y=toplot$ZNS, pch=19, col=colors[2])
axis(1, at=seq(0, 1, by=0.1), lab=seq(0, 1, by=0.1))
axis(2, at=seq(round(min(toplot), 0), 12, 1))

#FIRING vs. TOTAL RESPONSES
plot.new()
plot.window(xlim=c(0, 1), ylim=c(min(toplot), 12))
colors <- c("steelblue", "indianred")
points(x=toplot$TOTALresp, y=toplot$ZDS, pch=19, col=colors[1])
points(x=toplot$TOTALresp, y=toplot$ZNS, pch=19, col=colors[2])
axis(1, at=seq(0, 1, by=0.1), lab=seq(0, 1, by=0.1))
axis(2, at=seq(round(min(toplot), 0), 12, 1))


################## PLOTTING NEURAL HISTOGRAMS ################################

## 1. SELECTING THE RIGHT DATA
#Come up with an index (idx) to select the sessions of each animal in sequential order. Useful for selecting data from nexdata and such
allfiles <- list.files(NEXfilesSource)
nexIdx <- data.frame(rat=substr(allfiles, 10, 12), session=substr(allfiles, 22, 22), idx=1:length(allfiles))
uniqueRats <- unique(nexIdx$rat)

idx <- list()
for (i in 1:length(uniqueRats)){
        name <- as.character(uniqueRats[i])
        tmp <- subset(nexIdx, nexIdx$rat== uniqueRats[i])$idx
        idx[[name]] <- tmp
}


# Make a data frame with the data I want to plot

toplot <- list()
for(i in 1:length(uniqueRats)){
    name <- as.character(uniqueRats[i])
    for(j in 1:length(idx[[name]])){
            choose <- idx[[name]][j]
            tmp <- data.frame(rat=as.character(uniqueRats[i]),
                              session=j,
                              nNeuronsDS=nNeuronsDS[[choose]],
                              bin=seq(-psthmin, psthmax-psthmax/binw, by=psthmax/binw),
                              meanFreqPerBinDS=meanFreqPerBinDS[[choose]],
                              semFreqPerBinDS=semFreqPerBinDS[[choose]],
                              meanFreqPerBinNS=meanFreqPerBinNS[[choose]],
                              semFreqPerBinNS=semFreqPerBinNS[[choose]])
            toplot[[name]][[j]] <- tmp
    }
}

dataObjectsFolder <- "F:/Experiment 4/Neuronal data/Data for R/"
save(toplot, file= paste(dataObjectsFolder, "toplot.rdat", sep=""))



## 2. SETTINGS FOR THE GRAPH 
graphFolder <- "F:/Experiment 4/Neuronal data/Graphs/"
colindx <- c('blue', "indianred")

for(i in 1:length(toplot)){
        for(j in 1:length(toplot[[i]])){
         
                PlotSelection <- toplot[[i]][[j]]
                
                graphName <- paste("MV", PlotSelection$rat[1], "Session", PlotSelection$session[1])
                pdf(paste(graphFolder, graphName, ".pdf", sep=""))
                
                plot.new()
                plot.window(xlim=c(-psthmin, psthmax), ylim=c(0, 20))
                
                axis(1, at=seq(-psthmin, psthmax, by=binw/100), 
                     labels=seq(-psthmin, psthmax, by=binw/100), cex.axis = 1, las=1)
                axis(2, at = seq(0, 20, by=2) , cex.axis = 1, las = 2, pos=-psthmin)
                abline(v=0, col="red", lwd=2)
                
                xcoords <-seq(-psthmin, psthmax-binw/1000, by=binw/1000)
                lines(x=xcoords, y=PlotSelection$meanFreqPerBinDS, lwd=1.5, col=colindx[1]) #DS mean firing per bin
                lines(x=xcoords, y=PlotSelection$meanFreqPerBinNS, lwd=1.5, col=colindx[2]) #NS mean firing per bin
                
                #DS mean firing error cloud
                testcol=c(as.vector (col2rgb(colindx[1],alpha=F)[,1]))
                polcol=rgb(testcol[1],testcol[2],testcol[3],100, names = NULL, maxColorValue = 255)
                polygon(c(xcoords,rev(xcoords)), c(PlotSelection$meanFreqPerBinDS+PlotSelection$semFreqPerBinDS, rev(PlotSelection$meanFreqPerBinDS-PlotSelection$semFreqPerBinDS)), density=-20, col= polcol,border=NA)
                
                #NS mean firing error cloud
                testcol=c(as.vector (col2rgb(colindx[2],alpha=F)[,1]))
                polcol=rgb(testcol[1],testcol[2],testcol[3],100, names = NULL, maxColorValue = 255)
                polygon(c(xcoords,rev(xcoords)), c(PlotSelection$meanFreqPerBinNS+PlotSelection$semFreqPerBinNS, rev(PlotSelection$meanFreqPerBinNS-PlotSelection$semFreqPerBinNS)), density=-20, col= polcol,border=NA)
                
                #Title and legend
                mtext("Time from cue onset (s)", side = 1, line = 3, cex= 1.5)
                mtext("Firing rate (Hz)", side = 2, line = 2, cex=1.5)
                
                mtext(paste("Rat=MV", PlotSelection$rat[1], "/ Session=", PlotSelection$session[1]), 
                      side=3, adj=0.1, line=-2, font=2)
                mtext(paste("# Neurons=", PlotSelection$nNeuronsDS[1]), side=3, adj=0.2, line=-4)
                legend("topright", legend=c("S+", "S-"), fill=colindx)
                
                dev.off()
                
        }
}



